import type { Device } from "@/lib/types";

export const devices: Device[] = [
  {
    slug: "autonomous-quadcopter-drone",
    name: "Autonomous Quadcopter Drone",
    category: "Robotics",
    shortDescription:
      "UAV with onboard sensors, cameras, and processors for autonomous flight paths and real-time response.",
    image: "/images/devices/autonomous-quadcopter-drone.jpg",
    model3d: "/models/autonomous-quadcopter-drone.glb",
    specs: [
      { label: "Type", value: "Quadcopter UAV" },
      { label: "Flight Mode", value: "Autonomous / Manual" },
      { label: "Sensors", value: "GPS, IMU, Barometer, Camera" },
      { label: "Processor", value: "Onboard edge compute" },
      { label: "Battery", value: "LiPo 4S" },
      { label: "Flight Time", value: "~25 min" },
    ],
    applications: [
      "Aerial photography & videography",
      "Surveillance & monitoring",
      "Precision agriculture",
      "Search & rescue operations",
    ],
    quantity: 1,
    color: "#FF6B6B",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "creality-cr5-pro-3d-printer",
    name: "Creality CR-5 Pro 3D Printer",
    category: "Fabrication",
    shortDescription:
      "FDM 3D printer for rapid prototyping, layering plastic filament from digital designs with precision.",
    image: "/images/devices/creality-cr5-pro-3d-printer.jpg",
    model3d: "/models/creality-cr5-pro-3d-printer.glb",
    specs: [
      { label: "Technology", value: "FDM (Fused Deposition Modeling)" },
      { label: "Build Volume", value: "300 × 225 × 380 mm" },
      { label: "Layer Resolution", value: "0.1–0.4 mm" },
      { label: "Nozzle Temp", value: "Up to 260°C" },
      { label: "Bed Temp", value: "Up to 100°C" },
      { label: "Filament", value: "PLA, ABS, PETG, TPU" },
    ],
    applications: [
      "Rapid prototyping",
      "Custom manufacturing",
      "Hobbyist & educational projects",
      "Robotics part fabrication",
    ],
    quantity: 1,
    color: "#4ECDC4",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "intel-up-squared-edge-compute-kit",
    name: "Intel UP Squared / UP Xtreme Edge Compute Kit",
    category: "Edge Compute",
    shortDescription:
      "Single-board edge AI computer with Intel Movidius Myriad X VPU, 16GB+ RAM, and vision camera support.",
    image: "/images/devices/intel-up-squared-edge-compute-kit.jpg",
    model3d: "/models/intel-up-squared-edge-compute-kit.glb",
    specs: [
      { label: "Processor", value: "Intel Celeron / Core i5" },
      { label: "AI Accelerator", value: "Movidius Myriad X VPU" },
      { label: "RAM", value: "16 GB+" },
      { label: "Storage", value: "500 GB SSD" },
      { label: "Camera", value: "Intel Vision Camera module" },
      { label: "OS", value: "Ubuntu / Windows IoT" },
    ],
    applications: [
      "Computer vision at the edge",
      "AI inferencing without cloud dependency",
      "Real-time object detection",
      "IoT gateway prototyping",
    ],
    quantity: 1,
    color: "#A78BFA",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "intel-make-server",
    name: "Intel MAKE 1U / 2U Dual Socket Server",
    category: "Server",
    shortDescription:
      "Dual-CPU-socket compute server for data processing, model training, and parallel workloads.",
    image: "/images/devices/intel-make-server.jpg",
    model3d: "/models/intel-make-server.glb",
    specs: [
      { label: "Form Factor", value: "1U / 2U Rack Mount" },
      { label: "Sockets", value: "Dual CPU Socket" },
      { label: "Processor", value: "Intel Xeon Scalable" },
      { label: "RAM", value: "Up to 512 GB DDR4" },
      { label: "Storage", value: "Multiple NVMe / SATA bays" },
      { label: "Network", value: "Dual 10GbE" },
    ],
    applications: [
      "Deep learning model training",
      "Data center simulation",
      "HPC coursework",
      "Batch data processing",
    ],
    quantity: 1,
    color: "#6366F1",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "iot-trainer-kit-raspberry-pi",
    name: "IoT Trainer Kit — Raspberry Pi 3",
    category: "Sensing",
    shortDescription:
      "Student IoT hands-on lab kits based on Raspberry Pi 3 for sensor networking and embedded projects.",
    image: "/images/devices/iot-trainer-kit-raspberry-pi.jpg",
    model3d: "/models/iot-trainer-kit-raspberry-pi.glb",
    specs: [
      { label: "Board", value: "Raspberry Pi 3 Model B+" },
      { label: "Processor", value: "BCM2837B0 1.4 GHz Quad-core" },
      { label: "RAM", value: "1 GB LPDDR2" },
      { label: "Connectivity", value: "Wi-Fi, Bluetooth, Ethernet" },
      { label: "GPIO", value: "40-pin header" },
      { label: "Kit Includes", value: "Sensors, breadboard, jumper wires" },
    ],
    applications: [
      "Student IoT hands-on labs",
      "Sensor networking experiments",
      "Home automation prototypes",
      "Embedded systems coursework",
    ],
    quantity: 35,
    color: "#10B981",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "cisco-sg350-switch",
    name: "Cisco SG350 24-Port Switch",
    category: "Networking",
    shortDescription:
      "Enterprise-grade managed switch with 24 Gigabit ports for lab networking and IoT infrastructure.",
    image: "/images/devices/cisco-sg350-switch.jpg",
    model3d: "/models/cisco-sg350-switch.glb",
    specs: [
      { label: "Ports", value: "24 × Gigabit Ethernet" },
      { label: "Uplinks", value: "2 × SFP combo" },
      { label: "Management", value: "Web UI, CLI, SNMP" },
      { label: "Features", value: "VLAN, QoS, ACL, IGMP" },
      { label: "Switching Capacity", value: "52 Gbps" },
      { label: "PoE", value: "Optional PoE+ model" },
    ],
    applications: [
      "Lab network infrastructure",
      "IoT device connectivity",
      "Network management coursework",
      "VLAN segmentation demos",
    ],
    quantity: 1,
    color: "#0EA5E9",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "lorawan-multichannel-gateway",
    name: "LoRaWAN Multichannel Gateway",
    category: "Networking",
    shortDescription:
      "Long-range, low-power IoT gateway for smart agriculture, smart city, and wide-area sensor deployments.",
    image: "/images/devices/lorawan-multichannel-gateway.jpg",
    model3d: "/models/lorawan-multichannel-gateway.glb",
    specs: [
      { label: "Protocol", value: "LoRaWAN Class A/B/C" },
      { label: "Channels", value: "8 multichannel" },
      { label: "Range", value: "Up to 15 km (rural)" },
      { label: "Frequency", value: "IN865 (India)" },
      { label: "Backhaul", value: "Ethernet / Wi-Fi / 4G" },
      { label: "Power", value: "PoE / DC adapter" },
    ],
    applications: [
      "Smart agriculture monitoring",
      "Smart city sensor networks",
      "Long-range environmental sensing",
      "Industrial IoT pilots",
    ],
    quantity: 1,
    color: "#F59E0B",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "lerobot-so101-robotic-arm",
    name: "Lerobot SO-101 Robotic Arm",
    category: "Robotics",
    shortDescription:
      "Programmable robotic arm for building circuits, Sim2Real transfer, and vision-language AI model training.",
    image: "/images/devices/lerobot-so101-robotic-arm.jpg",
    model3d: "/models/lerobot-so101-robotic-arm.glb",
    specs: [
      { label: "Axes", value: "6 DOF (Degrees of Freedom)" },
      { label: "Payload", value: "~500g" },
      { label: "Control", value: "USB / Serial / ROS" },
      { label: "Integration", value: "Vision-Language Models" },
      { label: "Software", value: "LeRobot SDK, Python" },
      { label: "Use Case", value: "Sim2Real / Real2Sim" },
    ],
    applications: [
      "Building electrical circuits autonomously",
      "Sim2Real / Real2Sim transfer learning",
      "Vision-language integration research",
      "AI model training for manipulation",
    ],
    quantity: 1,
    color: "#EC4899",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "rplidar-a2-360",
    name: "RPLIDAR A2 (360°)",
    category: "Sensing",
    shortDescription:
      "360-degree 2D LIDAR scanner for SLAM, autonomous indoor mapping, and obstacle avoidance on robots.",
    image: "/images/devices/rplidar-a2-360.jpg",
    model3d: "/models/rplidar-a2-360.glb",
    specs: [
      { label: "Scan Range", value: "360° omnidirectional" },
      { label: "Distance", value: "Up to 12 m" },
      { label: "Sample Rate", value: "8000 samples/sec" },
      { label: "Angular Resolution", value: "0.45°" },
      { label: "Interface", value: "UART / USB" },
      { label: "Rotation Speed", value: "5–15 Hz" },
    ],
    applications: [
      "SLAM-based robot navigation",
      "Autonomous indoor mapping",
      "Obstacle avoidance systems",
      "Human-following robots",
    ],
    quantity: 1,
    color: "#14B8A6",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "intel-realsense-d456",
    name: "Intel RealSense Depth Camera D456",
    category: "Sensing",
    shortDescription:
      "Stereo depth camera for outdoor environment mapping, autonomous vehicle perception, and drone robotics.",
    image: "/images/devices/intel-realsense-d456.jpg",
    model3d: "/models/intel-realsense-d456.glb",
    specs: [
      { label: "Depth Technology", value: "Active IR Stereo" },
      { label: "Range", value: "0.6–6 m (indoor/outdoor)" },
      { label: "Depth Resolution", value: "Up to 1280 × 720" },
      { label: "RGB Resolution", value: "1920 × 1080" },
      { label: "FPS", value: "Up to 90 fps" },
      { label: "Interface", value: "USB-C 3.1" },
    ],
    applications: [
      "Outdoor environment mapping",
      "Autonomous vehicle perception",
      "Drone / UGV robotics",
      "3D scanning & reconstruction",
    ],
    quantity: 1,
    color: "#8B5CF6",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "interactive-board",
    name: "Interactive Board",
    category: "Edge Compute",
    shortDescription:
      "Large-format interactive display for lab teaching sessions, presentations, and collaborative learning.",
    image: "/images/devices/interactive-board.jpg",
    model3d: "/models/interactive-board.glb",
    specs: [
      { label: "Display", value: "65–86 inch Interactive" },
      { label: "Resolution", value: "4K UHD" },
      { label: "Touch", value: "20-point multi-touch" },
      { label: "Built-in", value: "Android / Windows OS" },
      { label: "Connectivity", value: "HDMI, USB, Wi-Fi" },
      { label: "Software", value: "Whiteboard + annotation" },
    ],
    applications: [
      "Lab teaching sessions",
      "Interactive presentations",
      "Collaborative problem solving",
      "Remote lab demonstrations",
    ],
    quantity: 1,
    color: "#F97316",
    hasRealModel: false,
    hasRealPhoto: false,
  },
  {
    slug: "bench-tools-kit",
    name: "Bench Tools Kit",
    category: "Fabrication",
    shortDescription:
      "Bar code scanner, oscilloscope, bench DC power supply, and soldering station with fume extractor.",
    image: "/images/devices/bench-tools-kit.jpg",
    model3d: "/models/bench-tools-kit.glb",
    specs: [
      { label: "Oscilloscope", value: "Digital Storage, 2/4 channel" },
      { label: "Power Supply", value: "Bench DC, 0–30V / 0–5A" },
      { label: "Soldering Station", value: "Temperature-controlled" },
      { label: "Fume Extractor", value: "Activated carbon filter" },
      { label: "Bar Code Scanner", value: "1D/2D handheld" },
      { label: "Accessories", value: "Probes, tips, solder wire" },
    ],
    applications: [
      "Circuit debugging & signal analysis",
      "PCB assembly & repair",
      "Robotics hardware maintenance",
      "Electronics prototyping",
    ],
    quantity: 1,
    color: "#95E1D3",
    hasRealModel: false,
    hasRealPhoto: false,
  },
];
